# Generated by Django 2.1.4 on 2020-08-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200806_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='ordermedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='ordermedicine',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderMedicine',
        ),
    ]
